"""Thin per-state runner: assemble the real ``running-left`` row.

Config-only wrapper around the generalized ``scripts/state_row.build_state_row``
(see that module's docstring for the ping-pong/wobble/validation logic).
Pure image processing -- no network, no ``HERMES_HOME``.

Addendum #8 relabel: the 3 poses below were generated by
``scripts/generate_running_right_sequence.py`` (prompt asked for
RIGHTWARD-facing stride poses), but the model rendered them LEFTWARD-facing
instead (flagged as a visual caveat in Phase 2B addendum #7). Per the
human's zero-cost decision, rather than re-spending API budget to retry,
these real poses are used AS-IS as the source for ``running-left`` (they
already face left) -- only the row's *label* changes, not the pixels.
``running-right`` is now derived as a horizontal mirror of THIS row via
Hermes's own ``atlas.mirror_frames()`` -- see ``build_running_right_row.py``.
See ``docs/phase_results/PHASE_2B_HATCH_PET_RESULT.md`` addendum #8 for the
full rationale.

Usage:
    /home/chegusan/.hermes/hermes-agent/venv/bin/python3 \\
        scripts/build_running_left_row.py
"""

from __future__ import annotations

from pose_sequence import PROCESSED_DIR
from state_row import build_state_row

STATE = "running-left"
ROW_FRAME_COUNT = 8  # atlas.FRAME_COUNTS["running-left"], per Hermes's real ROW_SPECS

# Filenames keep the "running-right" prefix -- that's the state the
# generation prompts (scripts/generate_running_right_sequence.py) actually
# targeted, and renaming the files would obscure that history. The row
# these poses build is labeled "running-left" because that's what they
# actually rendered as (see module docstring above).
POSE_FILES = [
    PROCESSED_DIR / "running-right_pose1.png",
    PROCESSED_DIR / "running-right_pose2.png",
    PROCESSED_DIR / "running-right_pose3.png",
]


def main() -> None:
    build_state_row(STATE, POSE_FILES, ROW_FRAME_COUNT)


if __name__ == "__main__":
    main()
